Delay sn3218 import to init
pimoroni/trilobot-python pull request #29
Opened 2021-12-16 14:02 UTC by ZodiusInfuser

2022-01-31 15:41 UTC, Gadgetoid commented
Should look at migrating this over to https://github.com/pimoroni/sn3218-python

2022-01-31 18:05 UTC, Gadgetoid commented
To elaborate upon this, I have now release sn3218 v2.0.0 which changes the API to a class.

It includes a back-compat wrapper so it doesn't break all the libraries that currently use it (and so we have time to migrate them over to the new approach) but you should probably switch to the class-based approach in Trilobot.

Release here: https://pypi.org/project/sn3218/

You can move `import sn3218` back to the top of the file and then use `self.sn3218 = sn3218.SN3218()`. Everything else should work as-is.

2022-01-31 18:06 UTC, Gadgetoid requested changes
Needs to depend upon `sn3218 >= 2.0.0` then these class-based tweaks will work.

2022-01-31 18:06 UTC, Gadgetoid commented on library/trilobot/__init__.py
> +        import sn3218
Move back to top of file.

2022-01-31 18:06 UTC, Gadgetoid commented on library/trilobot/__init__.py
> +        self.sn3218 = sn3218
```python
self.sn3218 = sn3218.SN3218()
```

2022-02-09 16:21 UTC, Gadgetoid commented
> it doesn't break all the libraries that currently use it

plot twist: it broke Automation HAT anyway

2022-08-23 17:08 UTC, closed without merging

2022-08-23 17:09 UTC, ZodiusInfuser commented
See https://github.com/pimoroni/trilobot-python/pull/33